# Generated by Django 2.1.5 on 2019-02-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('string', models.CharField(max_length=20)),
                ('integer', models.IntegerField()),
            ],
        ),
    ]
